export interface Emoji {
	char: string;
	shortcode: string;
	aliases?: string[];
}

export const EMOJIS: Emoji[] = [
	{ char: '😄', shortcode: 'smile', aliases: ['happy', 'laugh'] },
	{ char: '😁', shortcode: 'grin', aliases: ['teeth', 'cheeky'] },
	{ char: '😂', shortcode: 'joy', aliases: ['lol', 'rofl'] },
	{ char: '😆', shortcode: 'laughing', aliases: ['satisfied', 'haha'] },
	{ char: '😉', shortcode: 'wink', aliases: ['flirt', 'sly'] },
	{ char: '😊', shortcode: 'blush', aliases: ['shy', 'warm'] },
	{ char: '😍', shortcode: 'heart_eyes', aliases: ['in_love', 'love_struck'] },
	{ char: '😘', shortcode: 'kissing_heart', aliases: ['kiss', 'smooch'] },
	{ char: '😛', shortcode: 'tongue', aliases: ['silly', 'playful'] },
	{ char: '😎', shortcode: 'sunglasses', aliases: ['cool', 'chill'] },
	{ char: '🤔', shortcode: 'thinking', aliases: ['hmm', 'think'] },
	{ char: '🙄', shortcode: 'rolling_eyes', aliases: ['eyeroll', 'annoyed'] },
	{ char: '😒', shortcode: 'unamused', aliases: ['meh', 'bored'] },
	{ char: '😮', shortcode: 'astonished', aliases: ['open_mouth', 'surprised'] },
	{ char: '😱', shortcode: 'scream', aliases: ['horror', 'scared'] },
	{ char: '😡', shortcode: 'angry', aliases: ['rage', 'mad'] },
	{ char: '😔', shortcode: 'pensive', aliases: ['sad', 'blue'] },
	{ char: '😭', shortcode: 'sob', aliases: ['cry', 'crying'] },
	{ char: '😴', shortcode: 'sleepy', aliases: ['sleeping', 'tired'] },
	{ char: '🥳', shortcode: 'partying_face', aliases: ['party', 'birthday'] },
	{ char: '🤩', shortcode: 'star_struck', aliases: ['wow', 'amazed'] },
	{ char: '💀', shortcode: 'skull', aliases: ['dead', 'bones'] },
	{ char: '👍', shortcode: 'thumbsup', aliases: ['+1', 'yes', 'ok'] },
	{ char: '👎', shortcode: 'thumbsdown', aliases: ['-1', 'no', 'nope'] },
	{ char: '👏', shortcode: 'clap', aliases: ['applause', 'bravo'] },
	{ char: '🙏', shortcode: 'pray', aliases: ['thanks', 'please'] },
	{ char: '💪', shortcode: 'muscle', aliases: ['strong', 'flex'] },
	{ char: '👋', shortcode: 'wave', aliases: ['hello', 'hi'] },
	{ char: '❤️', shortcode: 'heart', aliases: ['love', 'red_heart'] },
	{ char: '🎉', shortcode: 'tada', aliases: ['celebrate', 'confetti'] },
	{ char: '🔥', shortcode: 'fire', aliases: ['hot', 'lit'] },
	{ char: '🚀', shortcode: 'rocket', aliases: ['ship', 'launch'] },
	{ char: '✨', shortcode: 'sparkles', aliases: ['sparkle', 'magic'] },
	{ char: '💡', shortcode: 'bulb', aliases: ['idea', 'lightbulb'] },
	{ char: '🐛', shortcode: 'bug', aliases: ['beetle', 'insect'] },
	{ char: '✅', shortcode: 'white_check_mark', aliases: ['check', 'done', 'green_check'] },
	{ char: '✔️', shortcode: 'heavy_check_mark', aliases: ['checkmark', 'verified'] },
	{ char: '❌', shortcode: 'x', aliases: ['cross', 'cancel', 'wrong'] },
	{ char: '⚠️', shortcode: 'warning', aliases: ['alert', 'warn'] },
	{ char: '🔀', shortcode: 'shuffle', aliases: ['crossed_arrows', 'swap', 'random'] },
	{ char: '⬆️', shortcode: 'arrow_up', aliases: ['up', 'north'] },
	{ char: '⬇️', shortcode: 'arrow_down', aliases: ['down', 'south'] },
	{ char: '⬅️', shortcode: 'arrow_left', aliases: ['left', 'west'] },
	{ char: '➡️', shortcode: 'arrow_right', aliases: ['right', 'east'] },
	{ char: '👀', shortcode: 'eyes', aliases: ['look', 'watch'] },
	{ char: '💯', shortcode: '100', aliases: ['hundred', 'perfect'] },
	{ char: '🏆', shortcode: 'trophy', aliases: ['winner', 'win'] },
	{ char: '🎁', shortcode: 'gift', aliases: ['present', 'reward'] },
	{ char: '🔒', shortcode: 'lock', aliases: ['locked', 'secure'] },
	{ char: '💰', shortcode: 'moneybag', aliases: ['money', 'cash'] }
];
